package greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import greendao.RutaDao;
import greendao.CoordenadaDao;
import greendao.Tipo_obstaculoDao;
import greendao.ObstaculoDao;
import greendao.Tipo_punto_interesDao;
import greendao.Punto_interesDao;
import greendao.UsuarioDao;
import greendao.EstadisticaDao;
import greendao.InterseccionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        RutaDao.createTable(db, ifNotExists);
        CoordenadaDao.createTable(db, ifNotExists);
        Tipo_obstaculoDao.createTable(db, ifNotExists);
        ObstaculoDao.createTable(db, ifNotExists);
        Tipo_punto_interesDao.createTable(db, ifNotExists);
        Punto_interesDao.createTable(db, ifNotExists);
        UsuarioDao.createTable(db, ifNotExists);
        EstadisticaDao.createTable(db, ifNotExists);
        InterseccionDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        RutaDao.dropTable(db, ifExists);
        CoordenadaDao.dropTable(db, ifExists);
        Tipo_obstaculoDao.dropTable(db, ifExists);
        ObstaculoDao.dropTable(db, ifExists);
        Tipo_punto_interesDao.dropTable(db, ifExists);
        Punto_interesDao.dropTable(db, ifExists);
        UsuarioDao.dropTable(db, ifExists);
        EstadisticaDao.dropTable(db, ifExists);
        InterseccionDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(RutaDao.class);
        registerDaoClass(CoordenadaDao.class);
        registerDaoClass(Tipo_obstaculoDao.class);
        registerDaoClass(ObstaculoDao.class);
        registerDaoClass(Tipo_punto_interesDao.class);
        registerDaoClass(Punto_interesDao.class);
        registerDaoClass(UsuarioDao.class);
        registerDaoClass(EstadisticaDao.class);
        registerDaoClass(InterseccionDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
