package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Ruta;
import greendao.Tipo_Ruta;
import greendao.Tipos_de_una_Ruta;
import greendao.Coordenada;
import greendao.Tipo_obstaculo;
import greendao.Obstaculo;
import greendao.Tipo_punto_interes;
import greendao.Punto_interes;
import greendao.Usuario;
import greendao.Estadistica;
import greendao.Interseccion;

import greendao.RutaDao;
import greendao.Tipo_RutaDao;
import greendao.Tipos_de_una_RutaDao;
import greendao.CoordenadaDao;
import greendao.Tipo_obstaculoDao;
import greendao.ObstaculoDao;
import greendao.Tipo_punto_interesDao;
import greendao.Punto_interesDao;
import greendao.UsuarioDao;
import greendao.EstadisticaDao;
import greendao.InterseccionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rutaDaoConfig;
    private final DaoConfig tipo_RutaDaoConfig;
    private final DaoConfig tipos_de_una_RutaDaoConfig;
    private final DaoConfig coordenadaDaoConfig;
    private final DaoConfig tipo_obstaculoDaoConfig;
    private final DaoConfig obstaculoDaoConfig;
    private final DaoConfig tipo_punto_interesDaoConfig;
    private final DaoConfig punto_interesDaoConfig;
    private final DaoConfig usuarioDaoConfig;
    private final DaoConfig estadisticaDaoConfig;
    private final DaoConfig interseccionDaoConfig;

    private final RutaDao rutaDao;
    private final Tipo_RutaDao tipo_RutaDao;
    private final Tipos_de_una_RutaDao tipos_de_una_RutaDao;
    private final CoordenadaDao coordenadaDao;
    private final Tipo_obstaculoDao tipo_obstaculoDao;
    private final ObstaculoDao obstaculoDao;
    private final Tipo_punto_interesDao tipo_punto_interesDao;
    private final Punto_interesDao punto_interesDao;
    private final UsuarioDao usuarioDao;
    private final EstadisticaDao estadisticaDao;
    private final InterseccionDao interseccionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rutaDaoConfig = daoConfigMap.get(RutaDao.class).clone();
        rutaDaoConfig.initIdentityScope(type);

        tipo_RutaDaoConfig = daoConfigMap.get(Tipo_RutaDao.class).clone();
        tipo_RutaDaoConfig.initIdentityScope(type);

        tipos_de_una_RutaDaoConfig = daoConfigMap.get(Tipos_de_una_RutaDao.class).clone();
        tipos_de_una_RutaDaoConfig.initIdentityScope(type);

        coordenadaDaoConfig = daoConfigMap.get(CoordenadaDao.class).clone();
        coordenadaDaoConfig.initIdentityScope(type);

        tipo_obstaculoDaoConfig = daoConfigMap.get(Tipo_obstaculoDao.class).clone();
        tipo_obstaculoDaoConfig.initIdentityScope(type);

        obstaculoDaoConfig = daoConfigMap.get(ObstaculoDao.class).clone();
        obstaculoDaoConfig.initIdentityScope(type);

        tipo_punto_interesDaoConfig = daoConfigMap.get(Tipo_punto_interesDao.class).clone();
        tipo_punto_interesDaoConfig.initIdentityScope(type);

        punto_interesDaoConfig = daoConfigMap.get(Punto_interesDao.class).clone();
        punto_interesDaoConfig.initIdentityScope(type);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        estadisticaDaoConfig = daoConfigMap.get(EstadisticaDao.class).clone();
        estadisticaDaoConfig.initIdentityScope(type);

        interseccionDaoConfig = daoConfigMap.get(InterseccionDao.class).clone();
        interseccionDaoConfig.initIdentityScope(type);

        rutaDao = new RutaDao(rutaDaoConfig, this);
        tipo_RutaDao = new Tipo_RutaDao(tipo_RutaDaoConfig, this);
        tipos_de_una_RutaDao = new Tipos_de_una_RutaDao(tipos_de_una_RutaDaoConfig, this);
        coordenadaDao = new CoordenadaDao(coordenadaDaoConfig, this);
        tipo_obstaculoDao = new Tipo_obstaculoDao(tipo_obstaculoDaoConfig, this);
        obstaculoDao = new ObstaculoDao(obstaculoDaoConfig, this);
        tipo_punto_interesDao = new Tipo_punto_interesDao(tipo_punto_interesDaoConfig, this);
        punto_interesDao = new Punto_interesDao(punto_interesDaoConfig, this);
        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);
        estadisticaDao = new EstadisticaDao(estadisticaDaoConfig, this);
        interseccionDao = new InterseccionDao(interseccionDaoConfig, this);

        registerDao(Ruta.class, rutaDao);
        registerDao(Tipo_Ruta.class, tipo_RutaDao);
        registerDao(Tipos_de_una_Ruta.class, tipos_de_una_RutaDao);
        registerDao(Coordenada.class, coordenadaDao);
        registerDao(Tipo_obstaculo.class, tipo_obstaculoDao);
        registerDao(Obstaculo.class, obstaculoDao);
        registerDao(Tipo_punto_interes.class, tipo_punto_interesDao);
        registerDao(Punto_interes.class, punto_interesDao);
        registerDao(Usuario.class, usuarioDao);
        registerDao(Estadistica.class, estadisticaDao);
        registerDao(Interseccion.class, interseccionDao);
    }
    
    public void clear() {
        rutaDaoConfig.getIdentityScope().clear();
        tipo_RutaDaoConfig.getIdentityScope().clear();
        tipos_de_una_RutaDaoConfig.getIdentityScope().clear();
        coordenadaDaoConfig.getIdentityScope().clear();
        tipo_obstaculoDaoConfig.getIdentityScope().clear();
        obstaculoDaoConfig.getIdentityScope().clear();
        tipo_punto_interesDaoConfig.getIdentityScope().clear();
        punto_interesDaoConfig.getIdentityScope().clear();
        usuarioDaoConfig.getIdentityScope().clear();
        estadisticaDaoConfig.getIdentityScope().clear();
        interseccionDaoConfig.getIdentityScope().clear();
    }

    public RutaDao getRutaDao() {
        return rutaDao;
    }

    public Tipo_RutaDao getTipo_RutaDao() {
        return tipo_RutaDao;
    }

    public Tipos_de_una_RutaDao getTipos_de_una_RutaDao() {
        return tipos_de_una_RutaDao;
    }

    public CoordenadaDao getCoordenadaDao() {
        return coordenadaDao;
    }

    public Tipo_obstaculoDao getTipo_obstaculoDao() {
        return tipo_obstaculoDao;
    }

    public ObstaculoDao getObstaculoDao() {
        return obstaculoDao;
    }

    public Tipo_punto_interesDao getTipo_punto_interesDao() {
        return tipo_punto_interesDao;
    }

    public Punto_interesDao getPunto_interesDao() {
        return punto_interesDao;
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

    public EstadisticaDao getEstadisticaDao() {
        return estadisticaDao;
    }

    public InterseccionDao getInterseccionDao() {
        return interseccionDao;
    }

}
