package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ESTADISTICA.
 */
public class Estadistica {

    private Long id;
    private String tiempo_recorrido;
    private java.util.Date fecha;
    private Integer id_usuario;
    private Integer id_ruta;

    public Estadistica() {
    }

    public Estadistica(Long id) {
        this.id = id;
    }

    public Estadistica(Long id, String tiempo_recorrido, java.util.Date fecha, Integer id_usuario, Integer id_ruta) {
        this.id = id;
        this.tiempo_recorrido = tiempo_recorrido;
        this.fecha = fecha;
        this.id_usuario = id_usuario;
        this.id_ruta = id_ruta;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTiempo_recorrido() {
        return tiempo_recorrido;
    }

    public void setTiempo_recorrido(String tiempo_recorrido) {
        this.tiempo_recorrido = tiempo_recorrido;
    }

    public java.util.Date getFecha() {
        return fecha;
    }

    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    public Integer getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(Integer id_usuario) {
        this.id_usuario = id_usuario;
    }

    public Integer getId_ruta() {
        return id_ruta;
    }

    public void setId_ruta(Integer id_ruta) {
        this.id_ruta = id_ruta;
    }

}
