package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table OBSTACULO.
 */
public class Obstaculo {

    private Long id;
    private String descripcion;
    private Integer id_tipo_obstaculo;
    private Integer id_coordenada;

    public Obstaculo() {
    }

    public Obstaculo(Long id) {
        this.id = id;
    }

    public Obstaculo(Long id, String descripcion, Integer id_tipo_obstaculo, Integer id_coordenada) {
        this.id = id;
        this.descripcion = descripcion;
        this.id_tipo_obstaculo = id_tipo_obstaculo;
        this.id_coordenada = id_coordenada;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getId_tipo_obstaculo() {
        return id_tipo_obstaculo;
    }

    public void setId_tipo_obstaculo(Integer id_tipo_obstaculo) {
        this.id_tipo_obstaculo = id_tipo_obstaculo;
    }

    public Integer getId_coordenada() {
        return id_coordenada;
    }

    public void setId_coordenada(Integer id_coordenada) {
        this.id_coordenada = id_coordenada;
    }

}
