package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUNTO_INTERES.
 */
public class Punto_interes extends Indicador {

    private Long id;
    private String descripcion;
    private Integer id_tipo_punto_interes;
    private Double latitud;
    private Double longitud;
    private Integer id_ruta;

    public Punto_interes() {
    }

    public Punto_interes(Long id) {
        this.id = id;
    }

    public Punto_interes(Long id, String descripcion, Integer id_tipo_punto_interes, Double latitud, Double longitud, Integer id_ruta) {
        this.id = id;
        this.descripcion = descripcion;
        this.id_tipo_punto_interes = id_tipo_punto_interes;
        this.latitud = latitud;
        this.longitud = longitud;
        this.id_ruta = id_ruta;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getId_tipo_punto_interes() {
        return id_tipo_punto_interes;
    }

    public void setId_tipo_punto_interes(Integer id_tipo_punto_interes) {
        this.id_tipo_punto_interes = id_tipo_punto_interes;
    }

    public Double getLatitud() {
        return latitud;
    }

    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }

    public Double getLongitud() {
        return longitud;
    }

    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

    public Integer getId_ruta() {
        return id_ruta;
    }

    public void setId_ruta(Integer id_ruta) {
        this.id_ruta = id_ruta;
    }

}
