package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUNTO_INTERES.
 */
public class Punto_interes {

    private Long id;
    private String descripcion;
    private Integer id_tipo_punto_interes;
    private Integer id_coordenada;

    public Punto_interes() {
    }

    public Punto_interes(Long id) {
        this.id = id;
    }

    public Punto_interes(Long id, String descripcion, Integer id_tipo_punto_interes, Integer id_coordenada) {
        this.id = id;
        this.descripcion = descripcion;
        this.id_tipo_punto_interes = id_tipo_punto_interes;
        this.id_coordenada = id_coordenada;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getId_tipo_punto_interes() {
        return id_tipo_punto_interes;
    }

    public void setId_tipo_punto_interes(Integer id_tipo_punto_interes) {
        this.id_tipo_punto_interes = id_tipo_punto_interes;
    }

    public Integer getId_coordenada() {
        return id_coordenada;
    }

    public void setId_coordenada(Integer id_coordenada) {
        this.id_coordenada = id_coordenada;
    }

}
