package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REGION.
 */
public class Region {

    private Long id;
    private String nombre;
    private String ordinal;

    public Region() {
    }

    public Region(Long id) {
        this.id = id;
    }

    public Region(Long id, String nombre, String ordinal) {
        this.id = id;
        this.nombre = nombre;
        this.ordinal = ordinal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getOrdinal() {
        return ordinal;
    }

    public void setOrdinal(String ordinal) {
        this.ordinal = ordinal;
    }

}
