package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYNC.
 */
public class Sync {

    private Long id;
    private String tabla;
    private String tiempo;

    public Sync() {
    }

    public Sync(Long id) {
        this.id = id;
    }

    public Sync(Long id, String tabla, String tiempo) {
        this.id = id;
        this.tabla = tabla;
        this.tiempo = tiempo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTabla() {
        return tabla;
    }

    public void setTabla(String tabla) {
        this.tabla = tabla;
    }

    public String getTiempo() {
        return tiempo;
    }

    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }

}
