package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TIPO_PUNTO_INTERES.
 */
public class Tipo_punto_interes {

    private Long id;
    private String nombre;
    private Integer id_icono;

    public Tipo_punto_interes() {
    }

    public Tipo_punto_interes(Long id) {
        this.id = id;
    }

    public Tipo_punto_interes(Long id, String nombre, Integer id_icono) {
        this.id = id;
        this.nombre = nombre;
        this.id_icono = id_icono;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getId_icono() {
        return id_icono;
    }

    public void setId_icono(Integer id_icono) {
        this.id_icono = id_icono;
    }

}
