package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TIPOS_DE_UNA__RUTA.
 */
public class Tipos_de_una_Ruta {

    private Integer id_ruta;
    private Integer id_tipo_ruta;

    public Tipos_de_una_Ruta() {
    }

    public Tipos_de_una_Ruta(Integer id_ruta, Integer id_tipo_ruta) {
        this.id_ruta = id_ruta;
        this.id_tipo_ruta = id_tipo_ruta;
    }

    public Integer getId_ruta() {
        return id_ruta;
    }

    public void setId_ruta(Integer id_ruta) {
        this.id_ruta = id_ruta;
    }

    public Integer getId_tipo_ruta() {
        return id_tipo_ruta;
    }

    public void setId_tipo_ruta(Integer id_tipo_ruta) {
        this.id_tipo_ruta = id_tipo_ruta;
    }

}
