package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TIPO__RUTA.
 */
public class Tipo_Ruta {

    private Long id;
    private String nombre;

    public Tipo_Ruta() {
    }

    public Tipo_Ruta(Long id) {
        this.id = id;
    }

    public Tipo_Ruta(Long id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
